import { useState } from "react";
import { ArrowLeft, BookOpenText, CheckCircle2, ChevronRight, Globe2, GraduationCap, Headphones, HeartHandshake, MapPinned, MessageCircle, Mic, Save, Sparkles, Volume2 } from "lucide-react";
import AudioButton from "../components/ui/AudioButton";
import { conversationVoice } from "../services/conversationVoice";
import Adventures from "../components/immersion/Adventures";
import MeetTheCast from "../components/immersion/MeetTheCast";
import SidekickPortrait from "../components/ui/SidekickPortrait";
import { sidekicks } from "../data/sidekicks";
import { hapticPress } from "../utils/hapticFeedback";
import LanguageWorld from "../components/immersion/LanguageWorld";
import { languageWorlds } from "../data/worlds";
import PronunciationRecorder from "../components/ui/PronunciationRecorder";

const baseFeatures = [
  ["cast", "Meet the Cast", "Get to know your learning companions", HeartHandshake, "#F28C28"],
  ["adventures", "Adventures", "Explore settings and talk to people", MapPinned, "#F28C28"],
  ["coach", "Conversation Coach", "Practice real situations", MessageCircle, "#F28C28"],
  ["variations", "Language Variation", "Hear more than one valid form", Globe2, "#24745B"],
  ["speakers", "Native Speakers", "Authentic recordings library", Headphones, "#4338CA"],
  ["grammar", "Grammar Visualizer", "See language patterns change", GraduationCap, "#C95D3A"],
  ["missions", "Culture Missions", "Communicate with context", HeartHandshake, "#F6C445"],
  ["stories", "Stories", "Read, tap, and understand", BookOpenText, "#24745B"],
  ["daily", "Daily Phrase", "Useful language every day", Sparkles, "#F28C28"]
];

export default function ImmersionPage({ dark, data, progress, soundEnabled, onLoseHeart, onReward, companionId, onCompanionChange }) {
  const [feature, setFeature] = useState(null);
  const features = data.pronunciation ? [...baseFeatures, ["pronunciation", "Tone & Pronunciation", "Notice sound patterns safely", Volume2, "#4338CA"]] : baseFeatures;
  const card = dark ? "border-white/10 bg-[#1A201E]" : "border-black/8 bg-white";
  const companion = sidekicks.find(item => item.id === companionId) || sidekicks[0];
  const world = languageWorlds[data.languageId];
  const immersion = progress.immersion || {};
  const journey = [
    { id: "adventures", kicker: "Step 1 · Enter the scene", title: "Adventure", text: "Move through a real-life setting and choose what to say.", Icon: MapPinned, color: "#24745B", progress: immersion.completedAdventures?.length || 0 },
    { id: "coach", kicker: "Step 2 · Find your voice", title: "Conversation", text: "Respond naturally in practical, everyday exchanges.", Icon: MessageCircle, color: "#4338CA" },
    { id: "stories", kicker: "Step 3 · Follow the story", title: "Story", text: "Read in context, reveal translations, and save useful words.", Icon: BookOpenText, color: "#C95D3A", progress: immersion.completedStories?.length || 0 },
    { id: "missions", kicker: "Step 4 · Understand the moment", title: "Culture mission", text: "Make language choices with cultural context in mind.", Icon: HeartHandshake, color: "#F28C28", progress: immersion.completedMissions?.length || 0 }
  ];
  const secondary = features.filter(([id]) => !["adventures", "coach", "stories", "missions", "daily"].includes(id));
  const journeyDone = journey.reduce((total, item) => total + (item.progress || 0), 0);
  const featureId = typeof feature === "string" ? feature : feature?.id;
  if (feature) return <div><button onClick={() => setFeature(null)} className={`mb-5 flex min-h-11 items-center gap-2 rounded-xl px-3 font-black ${dark ? "bg-white/6" : "bg-black/5"}`}><ArrowLeft size={18}/> Immersion home</button><Feature feature={featureId} initialMissionId={feature?.missionId} initialStoryId={feature?.storyId} world={world} onOpenActivity={activity=>setFeature(activity.missionId?{id:"adventures",missionId:activity.missionId}:activity.storyId?{id:"stories",storyId:activity.storyId}:activity.feature)} dark={dark} data={data} progress={progress} soundEnabled={soundEnabled} onLoseHeart={onLoseHeart} onReward={onReward} companionId={companionId} onCompanionChange={onCompanionChange}/></div>;
  return <div className="mx-auto max-w-5xl">
    <section className="afri-pattern relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#C95D3A] via-[#F28C28] to-[#F6C445] p-7 text-white sm:p-9"><div className="relative z-10 max-w-2xl"><div className="text-xs font-black uppercase tracking-[.25em] text-white/70">{data.languageName} Immersion</div><h1 className="mt-2 text-4xl font-black sm:text-5xl">Step into the language.</h1><p className="mt-4 font-semibold leading-7 text-white/80">Meet characters, enter everyday settings, and learn through moments that feel alive.</p></div><div className="absolute -bottom-14 -right-10 size-56 rounded-full bg-white/10"/></section>

    <section className="relative mt-5 overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#173d33] via-[#24745B] to-[#4338CA] p-5 text-white sm:p-8">
      <div className="absolute inset-0 opacity-20" style={{backgroundImage:"radial-gradient(circle at 75% 25%, #F6C445 0, transparent 30%), linear-gradient(135deg, transparent 55%, #101312 100%)"}}/>
      <div className="relative grid items-center gap-4 sm:grid-cols-[minmax(0,1fr)_12rem]"><div><div className="text-xs font-black uppercase tracking-[.22em] text-[#F6C445]">Today’s recommendation</div><h2 className="mt-2 text-3xl font-black sm:text-4xl">{companion.name} is ready to explore.</h2><p className="mt-3 max-w-xl font-semibold leading-7 text-white/70">Start with an Adventure, meet someone in context, and use what you know to move the story forward.</p><button onClick={() => setFeature("adventures")} onPointerDown={hapticPress} className="afri-press mt-6 flex min-h-14 items-center gap-2 rounded-2xl bg-[#F28C28] px-6 font-black text-white">Enter today’s scene <ChevronRight size={19}/></button></div><SidekickPortrait character={companion} className="mx-auto size-40 rounded-[2rem] bg-white/10 sm:size-48" eager/></div>
    </section>

    {world && <button onClick={()=>setFeature("world")} onPointerDown={hapticPress} className="afri-press relative mt-5 flex min-h-28 w-full items-center gap-4 overflow-hidden rounded-[1.7rem] bg-gradient-to-r from-[#F6C445] to-[#F28C28] p-5 text-left text-[#1A201E] sm:p-6"><span className="grid size-16 shrink-0 place-items-center rounded-2xl bg-white/45 text-4xl">🌍</span><span className="min-w-0 flex-1"><span className="block text-xs font-black uppercase tracking-[.2em] opacity-55">New · AfriLingo World</span><span className="mt-1 block text-2xl font-black">Enter the Twi living world</span><span className="mt-1 block text-sm font-semibold opacity-65">Adventures, stories, culture, and games—one connected journey.</span></span><ChevronRight className="shrink-0"/></button>}

    <section className={`relative mt-5 overflow-hidden rounded-[1.7rem] border p-5 sm:p-6 ${card}`}><div className="absolute -right-6 -top-8 text-8xl opacity-10">💬</div><div className="relative flex items-start gap-4"><SidekickPortrait character={companion} className="size-14 shrink-0 rounded-2xl bg-[#F6C445]/20"/><div className="min-w-0 flex-1"><div className="text-xs font-black uppercase tracking-[.2em] text-[#F28C28]">Daily phrase</div><div className="mt-1 text-xl font-black">{data.dailyPhrases?.[0]?.native || "Your daily phrase is ready"}</div><div className="mt-1 text-sm font-semibold opacity-50">{data.dailyPhrases?.[0]?.english}</div><button onClick={() => setFeature("daily")} className="mt-3 font-black text-[#F28C28]">Practice with {companion.name} →</button></div></div></section>

    <div className="mt-9 flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#F28C28]">Your immersion journey</div><h2 className="mt-1 text-3xl font-black">Learn through the moment</h2></div><div className="text-right"><div className="text-2xl font-black text-[#24745B]">{journeyDone}</div><div className="text-xs font-bold opacity-40">moments completed</div></div></div>
    <div className="relative mt-6 space-y-4 before:absolute before:bottom-10 before:left-[1.45rem] before:top-10 before:w-1 before:rounded-full before:bg-gradient-to-b before:from-[#24745B] before:via-[#4338CA] before:to-[#F28C28] sm:before:left-[2rem]">
      {journey.map((item,index) => <button key={item.id} onClick={() => setFeature(item.id)} onPointerDown={hapticPress} className={`afri-press relative flex min-h-32 w-full items-center gap-4 rounded-[1.7rem] border p-4 pl-16 text-left sm:gap-6 sm:p-6 sm:pl-24 ${card}`}><span className="absolute left-3 z-10 grid size-12 place-items-center rounded-2xl border-4 border-white text-lg font-black text-white shadow-lg sm:left-5 sm:size-14" style={{backgroundColor:item.color}}>{index+1}</span><span className="hidden size-16 shrink-0 place-items-center rounded-2xl text-white sm:grid" style={{backgroundColor:item.color}}><item.Icon size={28}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-black uppercase tracking-[.16em]" style={{color:item.color}}>{item.kicker}</span><span className="mt-1 block text-2xl font-black">{item.title}</span><span className={`mt-1 block text-sm font-semibold leading-6 ${dark ? "text-white/45" : "text-black/45"}`}>{item.text}</span>{item.progress != null && <span className="mt-2 block text-xs font-black" style={{color:item.color}}>{item.progress} completed</span>}</span><ChevronRight className="shrink-0 opacity-30"/></button>)}
    </div>

    <details className={`group mt-7 rounded-[1.7rem] border ${card}`}><summary className="flex min-h-20 cursor-pointer list-none items-center gap-4 p-5"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#4338CA]/15 text-[#4338CA]"><GraduationCap/></span><span className="flex-1"><span className="block text-xl font-black">Practice tools</span><span className="block text-sm font-semibold opacity-45">Grammar, pronunciation, variation, and the cast</span></span><ChevronRight className="opacity-35 transition group-open:rotate-90"/></summary><div className="space-y-2 border-t border-current/10 p-4">{secondary.map(([id,title,subtitle,Icon,color]) => <button key={id} onClick={() => setFeature(id)} className={`flex min-h-16 w-full items-center gap-3 rounded-xl px-4 text-left ${dark ? "bg-white/5" : "bg-[#FFF8EE]"}`}><span className="grid size-10 shrink-0 place-items-center rounded-xl text-white" style={{backgroundColor:color}}><Icon size={19}/></span><span className="min-w-0 flex-1"><span className="block font-black">{title}</span><span className="block truncate text-xs font-semibold opacity-45">{subtitle}</span></span><ChevronRight size={17} className="opacity-30"/></button>)}</div></details>
  </div>;
}

function Feature({ feature, ...props }) {
  if (feature === "world") return <LanguageWorld {...props}/>;
  if (feature === "cast") return <MeetTheCast {...props}/>;
  if (feature === "adventures") return <Adventures {...props}/>;
  if (feature === "coach") return <Coach {...props}/>;
  if (feature === "variations") return <Variations {...props}/>;
  if (feature === "speakers") return <Speakers {...props}/>;
  if (feature === "grammar") return <Grammar {...props}/>;
  if (feature === "pronunciation") return <Pronunciation {...props}/>;
  if (feature === "missions") return <Missions {...props}/>;
  if (feature === "stories") return <Stories {...props}/>;
  return <DailyPhrase {...props}/>;
}

function SectionTitle({ eyebrow, title, text }) { return <div><div className="text-xs font-black uppercase tracking-[.22em] text-[#F28C28]">{eyebrow}</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl leading-7 opacity-55">{text}</p></div>; }
const surface = (dark) => dark ? "border-white/10 bg-[#1A201E]" : "border-black/8 bg-white";

function Coach({ dark, data }) {
  const [level, setLevel] = useState("beginner"); const [scenario, setScenario] = useState(null); const [choice, setChoice] = useState(null); const caps = conversationVoice.getCapabilities(data);
  const items = data.conversations.filter(item => item.level === level);
  if (scenario) { const turn=scenario.turns[0]; return <div><SectionTitle eyebrow="Conversation coach" title={scenario.title} text={scenario.context}/><div className={`mt-5 rounded-[1.7rem] border p-5 ${surface(dark)}`}><div className="rounded-2xl bg-[#24745B] p-4 text-white"><div className="text-xs font-black uppercase opacity-60">{turn.speaker}</div><div className="mt-2 text-xl font-black">{turn.native}</div><div className="mt-1 text-sm text-white/65">{turn.english}</div></div><div className="mt-4 flex gap-2"><button disabled={!caps.recognition} title={caps.recognition ? "Speak" : "Speech recognition adapter required"} className="flex min-h-12 items-center gap-2 rounded-xl bg-[#4338CA] px-4 font-black text-white disabled:cursor-not-allowed disabled:opacity-40"><Mic size={18}/> Speak response</button><span className="self-center text-xs font-bold opacity-45">{caps.recognition ? "Ready" : "Voice setup pending · use text choices"}</span></div><div className="mt-5 grid gap-2">{turn.choices.map(item => <button key={item} onClick={()=>setChoice(item)} className={`min-h-14 rounded-xl border p-3 text-left font-black ${choice===item ? "border-[#F28C28] bg-[#F28C28]/10" : dark ? "border-white/10" : "border-black/10"}`}>{item}</button>)}</div>{choice && <div className={`mt-4 rounded-xl p-4 ${choice===turn.answer ? "bg-[#24745B]/15" : "bg-[#C95D3A]/15"}`}><div className="font-black">{choice===turn.answer ? "That fits the situation." : "Try the response that answers this situation directly."}</div><div className="mt-1 text-sm opacity-60">{turn.feedback}</div></div>}</div><button onClick={()=>{setScenario(null);setChoice(null)}} className="mt-4 font-black text-[#F28C28]">Choose another scenario</button></div>; }
  return <div><SectionTitle eyebrow="Voice-ready · text fallback active" title="Conversation Coach" text="The shared service layer is ready for verified recognition for the active language and feedback. Until an adapter is configured, scenarios provide honest text practice without simulated scoring."/><LevelTabs value={level} onChange={setLevel}/><div className="mt-5 grid gap-3 sm:grid-cols-2">{items.map(item=><button key={item.id} onClick={()=>setScenario(item)} className={`rounded-[1.5rem] border p-5 text-left ${surface(dark)}`}><div className="text-3xl">{item.emoji}</div><div className="mt-3 text-xl font-black">{item.title}</div><div className="mt-2 text-sm opacity-50">{item.context}</div></button>)}</div></div>;
}

function Variations({ dark, data }) { return <div><SectionTitle eyebrow="Regional & contextual awareness" title="Language Variation" text="Learn alternatives without ranking legitimate forms as wrong. Region labels stay broad unless a verified source supports something more specific."/><div className="mt-5 space-y-3">{data.variations.map(item=><details key={item.id} className={`rounded-[1.5rem] border p-5 ${surface(dark)}`}><summary className="cursor-pointer list-none"><div className="text-xs font-black uppercase tracking-wider text-[#24745B]">Common form</div><div className="mt-1 text-2xl font-black">{item.common}</div><div className="mt-1 opacity-50">{item.meaning}</div></summary><div className="mt-5 border-t border-current/10 pt-5"><div className="text-xs font-black uppercase tracking-wider text-[#F28C28]">Another form you may hear</div><div className="mt-1 text-xl font-black">{item.alternative}</div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><Info label="Where" value={item.region}/><Info label="Register" value={item.formality}/><Info label="Context" value={item.context}/></div><p className="mt-4 text-sm leading-6 opacity-60">{item.explanation}</p></div></details>)}</div></div>; }

function Speakers({ dark, data }) { const [speed,setSpeed]=useState("normal"); return <div><SectionTitle eyebrow="Authentic audio only" title="Native Speaker Library" text="No recordings are fabricated. Contributor slots and playback modes are ready; every unavailable recording is clearly marked pending."/><LevelTabs value={speed} onChange={setSpeed} values={["slow","normal","natural"]}/><div className="mt-5 space-y-3">{data.speakers.map(item=><div key={item.id} className={`rounded-[1.5rem] border p-5 ${surface(dark)}`}><div className="flex items-start justify-between gap-3"><div><div className="text-xl font-black">{item.phrase}</div><div className="mt-1 opacity-50">{item.english}</div></div><AudioButton src={item.audio[speed]} label={`${item.label}, ${speed} speed`} compact className="bg-[#4338CA] text-white"/></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold opacity-55"><span>{item.label}</span><span>· {item.region}</span><span>· {item.style}</span></div><div className="mt-3 rounded-xl bg-[#F6C445]/15 p-3 text-sm font-bold">Recording pending contributor consent and verification.</div></div>)}</div></div>; }

function Grammar({ dark, data, progress, onReward }) { const [level,setLevel]=useState("beginner"); const [answers,setAnswers]=useState({}); const done=progress.immersion?.completedGrammar||[]; const items=data.grammar.filter(x=>x.level===level); return <div><SectionTitle eyebrow="Pattern first · terminology second" title="Grammar Visualizer" text="See the change before opening the technical explanation."/><LevelTabs value={level} onChange={setLevel}/><div className="mt-5 space-y-4">{items.map(item=>{const answer=answers[item.id];return <div key={item.id} className={`rounded-[1.6rem] border p-5 ${surface(dark)}`}><div className="font-black">{item.title}</div><div className="mt-1 text-sm opacity-50">{item.intro}</div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><Pattern value={item.before}/><ChevronRight/><Pattern value={item.after}/></div><details className="mt-4 rounded-xl bg-[#4338CA]/10 p-3"><summary className="cursor-pointer font-black">Why does it change?</summary><p className="mt-2 text-sm leading-6 opacity-65">{item.explanation}</p></details><div className="mt-4 text-sm font-black">{item.question.prompt}</div><div className="mt-2 flex flex-wrap gap-2">{item.question.options.map(option=><button key={option} onClick={()=>setAnswers(v=>({...v,[item.id]:option}))} className={`rounded-xl border px-3 py-2 font-black ${answer===option ? "border-[#F28C28] bg-[#F28C28]/10" : "border-current/10"}`}>{option}</button>)}</div>{answer&&<div className={`mt-3 text-sm font-bold ${answer===item.question.answer?"text-[#53B98A]":"text-[#C95D3A]"}`}>{answer===item.question.answer?"Pattern spotted!":item.question.explanation}</div>}{answer===item.question.answer&&!done.includes(item.id)&&<button onClick={()=>onReward({field:"completedGrammar",id:item.id,xp:10})} className="mt-3 rounded-xl bg-[#24745B] px-4 py-2 font-black text-white">Complete · +10 XP</button>}</div>})}</div></div>; }

function Missions({ dark,data,progress,onReward }) { const [selected,setSelected]=useState({});const done=progress.immersion?.completedMissions||[];return <div><SectionTitle eyebrow="Language + decisions + context" title="Culture Missions" text={`Practice practical communication in specific ${data.languageName} contexts without reducing communities to generic stereotypes.`}/><div className="mt-5 space-y-4">{data.missions.map(item=>{const answer=selected[item.id];const choice=item.choices.find(x=>x.text===answer);return <div key={item.id} className={`rounded-[1.6rem] border p-5 ${surface(dark)}`}><div className="text-3xl">{item.emoji}</div><h2 className="mt-2 text-xl font-black">{item.title}</h2><p className="mt-2 opacity-55">{item.context}</p><div className="mt-4 font-black">{item.prompt}</div><div className="mt-3 grid gap-2">{item.choices.map(option=><button key={option.text} onClick={()=>setSelected(v=>({...v,[item.id]:option.text}))} className={`min-h-12 rounded-xl border p-3 text-left font-black ${answer===option.text?"border-[#F28C28] bg-[#F28C28]/10":"border-current/10"}`}>{option.text}</button>)}</div>{choice&&<div className={`mt-3 rounded-xl p-3 text-sm font-semibold ${choice.correct?"bg-[#24745B]/15":"bg-[#C95D3A]/15"}`}>{choice.feedback}</div>}{choice?.correct&&<><div className="mt-3 rounded-xl bg-[#F6C445]/15 p-3 text-sm leading-6"><strong>Cultural context:</strong> {item.culture}</div>{!done.includes(item.id)&&<button onClick={()=>onReward({field:"completedMissions",id:item.id,xp:item.xp})} className="mt-3 rounded-xl bg-[#F28C28] px-4 py-2 font-black text-white">Complete mission · +{item.xp} XP</button>}</>}</div>})}</div></div>; }

function Stories({ dark,data,progress,onReward,initialStoryId }) { const [story,setStory]=useState(data.stories.find(item=>item.id===initialStoryId)||data.stories[0]);const [translations,setTranslations]=useState({});const [word,setWord]=useState(null);const saved=progress.immersion?.savedWords||[];return <div><SectionTitle eyebrow="Original learning stories" title={`${data.languageName} Stories`} text="These are clearly labeled AfriLingo learning stories—not unattributed traditional folktales. Verified traditional material can use the same reader later."/><div className="mt-5 flex flex-wrap gap-2">{data.stories.map(item=><button key={item.id} onClick={()=>{setStory(item);setTranslations({});setWord(null)}} className={`rounded-xl px-3 py-2 font-black ${story.id===item.id?"bg-[#F28C28] text-white":dark?"bg-white/6":"bg-black/5"}`}>{item.emoji} {item.englishTitle}</button>)}</div><article className={`mt-4 rounded-[1.7rem] border p-5 sm:p-7 ${surface(dark)}`}><div className="flex justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-wider text-[#24745B]">{story.origin} · {story.level}</div><h2 className="mt-2 text-3xl font-black">{story.title}</h2><div className="opacity-50">{story.englishTitle}</div></div><AudioButton src={story.audio} label={story.title} compact className="bg-[#4338CA] text-white"/></div><div className="mt-6 space-y-3">{story.sentences.map((sentence,index)=><button key={index} onClick={()=>setTranslations(v=>({...v,[index]:!v[index]}))} className={`block w-full rounded-xl p-4 text-left ${dark?"bg-white/5":"bg-black/[.035]"}`}><div className="text-lg font-black">{sentence.native.split(/\s+/).map((token,i)=>{const clean=token.toLocaleLowerCase().replace(/[^a-záéíóú]/g,"");const meaning=story.vocabulary[clean];return <span key={i} onClick={(event)=>{if(meaning){event.stopPropagation();setWord({token,meaning})}}} className={meaning?"mr-1 rounded bg-[#F6C445]/20 px-1":"mr-1"}>{token}</span>})}</div>{translations[index]&&<div className="mt-2 text-sm opacity-55">{sentence.english}</div>}</button>)}</div>{word&&<div className="mt-4 flex items-center justify-between rounded-xl bg-[#24745B]/15 p-3"><div><strong>{word.token}</strong> · {word.meaning}</div><button onClick={()=>onReward({field:"savedWords",id:`${story.id}:${word.token}`,xp:0})} className="flex items-center gap-1 font-black text-[#24745B]"><Save size={16}/>{saved.includes(`${story.id}:${word.token}`)?"Saved":"Save"}</button></div>}<div className="mt-5 rounded-xl border border-current/10 p-4"><div className="font-black">{story.question.prompt}</div><div className="mt-3 flex flex-wrap gap-2">{story.question.options.map(option=><button key={option} onClick={()=>{if(option===story.question.answer)onReward({field:"completedStories",id:story.id,xp:15})}} className="rounded-xl bg-[#F28C28]/10 px-3 py-2 font-black">{option}</button>)}</div></div></article></div>; }

function DailyPhrase({ dark,data,progress,onReward }) { const [index,setIndex]=useState(0);const item=data.dailyPhrases[index];const saved=progress.immersion?.savedPhrases||[];const claimed=progress.immersion?.claimedDailyPhrases||[];return <div><SectionTitle eyebrow="Useful language, not random words" title={`Daily ${data.languageName} Phrase`} text="Save expressions, review previous phrases, and add a small amount of practice XP."/><div className={`mt-5 rounded-[1.8rem] border p-6 sm:p-8 ${surface(dark)}`}><div className="flex items-start justify-between"><div><div className="text-xs font-black uppercase tracking-wider text-[#F28C28]">Phrase {index+1} of {data.dailyPhrases.length}</div><h2 className="mt-3 text-4xl font-black">{item.native}</h2><div className="mt-2 text-xl opacity-60">{item.english}</div></div><AudioButton src={item.audio} label={item.native} compact className="bg-[#4338CA] text-white"/></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Literal sense" value={item.literal}/><Info label="When to use it" value={item.when}/></div><div className="mt-4 rounded-xl bg-[#F6C445]/15 p-4 text-sm leading-6">{item.context}</div><div className="mt-4"><div className="font-black">{item.exampleNative}</div><div className="mt-1 opacity-50">{item.exampleEnglish}</div></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>onReward({field:"savedPhrases",id:item.id,xp:0})} className="flex min-h-11 items-center gap-2 rounded-xl bg-[#24745B] px-4 font-black text-white"><Save size={17}/>{saved.includes(item.id)?"Saved":"Save phrase"}</button>{!claimed.includes(item.id)&&<button onClick={()=>onReward({field:"claimedDailyPhrases",id:item.id,xp:5})} className="min-h-11 rounded-xl bg-[#F28C28] px-4 font-black text-white">Practice · +5 XP</button>}</div></div><div className="mt-4 flex flex-wrap gap-2">{data.dailyPhrases.map((phrase,i)=><button key={phrase.id} onClick={()=>setIndex(i)} className={`grid size-11 place-items-center rounded-xl font-black ${i===index?"bg-[#F28C28] text-white":dark?"bg-white/6":"bg-black/5"}`}>{i+1}</button>)}</div></div>; }

function LevelTabs({value,onChange,values=["beginner","intermediate","advanced"]}) { return <div className="mt-5 grid grid-cols-3 gap-2">{values.map(item=><button key={item} onClick={()=>onChange(item)} className={`min-h-12 rounded-xl text-sm font-black capitalize ${value===item?"bg-[#F28C28] text-white":"bg-[#F28C28]/10 text-[#F28C28]"}`}>{item}</button>)}</div>; }
function Info({label,value}) { return <div className="rounded-xl bg-[#4338CA]/10 p-3"><div className="text-[10px] font-black uppercase tracking-wider text-[#7067FF]">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div>; }
function Pattern({value}) { return <div className="rounded-2xl bg-[#F28C28]/12 p-4 text-xl font-black text-[#F28C28]">{value}</div>; }

function Pronunciation({ dark, data, progress, onReward }) {
  const [index, setIndex] = useState(0);
  const item = data.pronunciation.items[index];
  const completed = progress.immersion?.completedPronunciation || [];
  const done = completed.includes(item.id);
  return <div><SectionTitle eyebrow="Hear it · notice it · say it" title={`${data.languageName} Tone & Pronunciation`} text={data.pronunciation.intro}/>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-2" aria-label="Pronunciation topics">{data.pronunciation.items.map((topic, topicIndex) => <button key={topic.id} onClick={() => setIndex(topicIndex)} aria-current={topicIndex === index ? "step" : undefined} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-black ${topicIndex === index ? "bg-[#4338CA] text-white" : dark ? "bg-white/7" : "bg-black/5"}`}>{completed.includes(topic.id) ? "✓ " : ""}{topicIndex + 1}. {topic.shortLabel || topic.focus}</button>)}</div>
    <article className={`mt-3 overflow-hidden rounded-[1.7rem] border ${surface(dark)}`}>
      <div className="bg-gradient-to-br from-[#4338CA] to-[#24745B] p-5 text-white sm:p-7"><div className="text-xs font-black uppercase tracking-[.2em] text-white/65">Practice {index + 1} of {data.pronunciation.items.length} · {item.focus}</div><div className="mt-4 text-4xl font-black sm:text-5xl">{item.native}</div><div className="mt-2 text-lg font-semibold text-white/65">{item.english}</div>{item.chunks?.length > 0 && <div className="mt-5 flex flex-wrap gap-2" aria-label="Phrase chunks">{item.chunks.map(chunk => <span key={chunk} className="rounded-xl bg-white/15 px-3 py-2 text-lg font-black">{chunk}</span>)}</div>}</div>
      <div className="p-5 sm:p-7"><div className="grid gap-3 sm:grid-cols-2"><Info label="Notice" value={item.note}/><Info label="Practice tip" value={item.practiceTip || "Say the complete form slowly, then repeat it at a comfortable pace."}/></div>
        <div className="mt-4 flex items-center justify-between gap-4 rounded-2xl bg-[#F6C445]/15 p-4"><div><div className="text-xs font-black uppercase tracking-wider text-[#C95D3A]">Reference audio</div><div className="mt-1 text-sm font-semibold opacity-60">{item.audio ? "Listen before recording yourself." : "Awaiting a licensed, verified Twi speaker recording."}</div></div><AudioButton src={item.audio} label={item.native} compact className="shrink-0 bg-[#4338CA] text-white"/></div>
        <PronunciationRecorder key={item.id} label={item.native} dark={dark}/>
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-xs font-semibold leading-5 opacity-45">Completion records practice—not pronunciation accuracy. Tone feedback will only be enabled with verified reference audio and a tested scoring model.</p>{!done ? <button onClick={() => onReward({field:"completedPronunciation",id:item.id,xp:5})} onPointerDown={hapticPress} className="afri-press min-h-11 rounded-xl bg-[#24745B] px-4 font-black text-white">Mark practiced · +5 XP</button> : <span className="flex min-h-11 items-center gap-2 rounded-xl bg-[#24745B]/15 px-4 font-black text-[#24745B]"><CheckCircle2 size={18}/>Practiced</span>}</div>
      </div>
    </article>
    <div className="mt-4 flex justify-between gap-3"><button disabled={index === 0} onClick={() => setIndex(value => value - 1)} className="min-h-11 rounded-xl px-4 font-black disabled:opacity-30">Previous</button><button disabled={index === data.pronunciation.items.length - 1} onClick={() => setIndex(value => value + 1)} className="min-h-11 rounded-xl bg-[#F28C28] px-5 font-black text-white disabled:opacity-30">Next practice</button></div>
  </div>;
}


