import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { CheckCircle2, Heart, RotateCcw, Sparkles, XCircle } from "lucide-react";
import QuestionRenderer, { expectedAnswer, normalizeAnswer } from "../components/lessons/QuestionRenderer";
import Lebo from "../components/ui/Lebo";

export default function ReviewPage({ dark, progress, language, onLoseHeart, onComplete }) {
  const items = useMemo(() => [...(progress.reviewQueue || [])].sort((a, b) => b.misses - a.misses || b.lastMissedAt - a.lastMissedAt), [progress.reviewQueue]);
  const [session, setSession] = useState(false);
  if (session && items.length) return <ReviewSession dark={dark} items={items} hearts={progress.hearts} languageId={language.id} onLoseHeart={onLoseHeart} onExit={() => setSession(false)} onComplete={(result) => { onComplete(result); setSession(false); }} />;
  const card = dark ? "border-white/10 bg-[#1A201E]" : "border-black/8 bg-white";
  return <div className="mx-auto max-w-3xl">
    <section className="afri-pattern overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#4338CA] to-[#24745B] p-6 text-white sm:p-8"><div className="flex items-center gap-5"><Lebo pose={items.length ? "encourage" : "celebrate"} reaction={items.length ? "idle" : "celebrate"} languageId={language.id} className="h-28 w-28 shrink-0" decorative/><div><div className="text-xs font-black uppercase tracking-[.24em] text-white/60">{language.language} practice</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">Review Hub</h1><p className="mt-2 font-semibold text-white/70">Turn mistakes into strong memories. Items disappear only after a correct review answer.</p></div></div></section>
    {!items.length ? <div className={`mt-5 rounded-[1.75rem] border p-8 text-center ${card}`}><div className="text-5xl">✨</div><h2 className="mt-4 text-2xl font-black">Review queue clear</h2><p className="mt-2 font-semibold opacity-50">New mistakes from lessons and Explore will appear here automatically.</p></div> : <><div className={`mt-5 rounded-[1.75rem] border p-5 ${card}`}><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-wider text-[#F28C28]">Ready to strengthen</div><div className="mt-1 text-3xl font-black">{items.length} {items.length === 1 ? "item" : "items"}</div></div><RotateCcw size={30} className="text-[#4338CA]"/></div><button disabled={progress.hearts === 0} onClick={() => setSession(true)} className="mt-5 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#F28C28] font-black text-white disabled:cursor-not-allowed disabled:opacity-40"><Sparkles size={19}/> Start review · up to +{items.length * 5} XP</button>{progress.hearts === 0 && <p className="mt-3 text-center text-sm font-bold text-[#C95D3A]">Recover a heart before reviewing.</p>}</div><div className="mt-4 space-y-3">{items.map(item => <div key={item.reviewKey} className={`flex items-center gap-3 rounded-2xl border p-4 ${card}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#4338CA]/10 font-black text-[#7067FF]">{item.misses}×</span><div className="min-w-0 flex-1"><div className="truncate font-black">{item.question.prompt}</div><div className="mt-1 truncate text-xs font-semibold opacity-45">{item.sourceTitle}</div></div></div>)}</div></>}
  </div>;
}

function ReviewSession({ dark, items, hearts, languageId, onLoseHeart, onExit, onComplete }) {
  const [index, setIndex] = useState(0); const [selected, setSelected] = useState(null); const [checked, setChecked] = useState(false); const [resolved, setResolved] = useState([]); const [mistakes, setMistakes] = useState(0);
  const currentItem = items[index]; const current = currentItem.question; const correct = normalizeAnswer(current, selected) === expectedAnswer(current); const progress = ((index + (checked ? 1 : 0)) / items.length) * 100;
  const submit = () => { if (selected == null || (Array.isArray(selected) && !selected.length)) return; setChecked(true); if (correct) setResolved(keys => [...new Set([...keys, currentItem.reviewKey])]); else { setMistakes(value => value + 1); onLoseHeart(); } };
  const next = () => { if (index + 1 >= items.length) return onComplete({ resolvedKeys: resolved, xp: resolved.length * 5 }); setIndex(value => value + 1); setSelected(null); setChecked(false); };
  return <div className="mx-auto max-w-2xl"><div className="mb-7 flex items-center gap-3"><button onClick={onExit} className={`grid size-11 place-items-center rounded-xl ${dark ? "bg-white/6" : "bg-black/5"}`} aria-label="Exit review"><RotateCcw size={19}/></button><div className={`h-3 flex-1 overflow-hidden rounded-full ${dark ? "bg-white/10" : "bg-black/10"}`}><motion.div className="h-full rounded-full bg-[#F28C28]" animate={{width:`${progress}%`}}/></div><div className="flex items-center gap-1 font-black text-[#EF5B5B]"><Heart size={20} fill="currentColor"/>{hearts}</div></div><div className="text-xs font-black uppercase tracking-[.22em] text-[#4338CA]">Review · {currentItem.sourceTitle}</div><h1 className="mt-2 text-3xl font-black">{current.prompt}</h1><div className="mt-6"><QuestionRenderer question={current} dark={dark} checked={checked} value={selected} onChange={setSelected}/></div>{checked && <div className={`mt-5 flex items-start gap-3 rounded-2xl border p-4 ${correct ? "border-[#24745B]/30 bg-[#24745B]/10" : "border-[#C95D3A]/30 bg-[#C95D3A]/10"}`}><Lebo pose={correct ? "encourage" : "learn"} reaction={correct ? "correct" : "encourage"} languageId={languageId} className="size-16 shrink-0" decorative/>{correct ? <CheckCircle2 className="text-[#53B98A]"/> : <XCircle className="text-[#C95D3A]"/>}<div><div className="font-black">{correct ? "Memory strengthened!" : "Keep this one in review."}</div><div className="mt-1 text-sm font-semibold opacity-55">{current.explanation}</div></div></div>}<button disabled={!checked && (selected == null || (Array.isArray(selected) && !selected.length))} onClick={checked ? next : submit} className={`mt-7 min-h-14 w-full rounded-2xl font-black text-white disabled:opacity-30 ${checked ? correct ? "bg-[#24745B]" : "bg-[#C95D3A]" : "bg-[#F28C28]"}`}>{checked ? index + 1 >= items.length ? `Finish · ${resolved.length * 5} XP` : "Continue" : "Check"}</button>{mistakes > 0 && <div className="mt-3 text-center text-xs font-bold opacity-40">{mistakes} still strengthening</div>}</div>;
}
