import { useRef, useState } from "react";
import { Download, FileUp, HelpCircle, Info, MessageSquareWarning, Mic, RotateCcw, ShieldCheck, Trash2, Volume2, VolumeX } from "lucide-react";
import { downloadLearningData, importLearningData, resetAllLearningData, resetCourseData } from "../services/progressBackup";
import { playUiSound } from "../services/uiSound";
import TesterReport from "../components/system/TesterReport";

export default function SettingsPage({ dark, language, unit, preferences, onPreferencesChange, onOpenAudioStudio }) {
  const inputRef=useRef(null); const [message,setMessage]=useState("");
  const card=dark?"border-white/10 bg-[#1A201E]":"border-black/8 bg-white";
  const importFile=async event=>{const file=event.target.files?.[0];if(!file)return;try{const count=await importLearningData(file);setMessage(`${count} saved areas restored. Reloading…`);window.setTimeout(()=>window.location.reload(),700)}catch(error){setMessage(error.message)}finally{event.target.value=""}};
  return <div className="mx-auto max-w-3xl"><div><div className="text-xs font-black uppercase tracking-[.22em] text-[#F28C28]">Control your experience</div><h1 className="mt-2 text-4xl font-black">Settings & Help</h1><p className="mt-3 font-semibold opacity-50">AfriLingo currently keeps prototype learning data on this device.</p></div>
    <Section title="Sound & celebration" icon={preferences.soundEnabled !== false ? Volume2 : VolumeX} card={card}><div className="flex items-center justify-between gap-4"><div><div className="font-black">Interface sounds</div><p className="mt-1 text-sm font-semibold leading-6 opacity-55">Hear feedback for answers, XP rewards, and lesson milestones.</p></div><button type="button" role="switch" aria-label="Interface sounds" aria-checked={preferences.soundEnabled !== false} onClick={()=>{const enabled=preferences.soundEnabled===false;onPreferencesChange({...preferences,soundEnabled:enabled});if(enabled)playUiSound("correct",true)}} className={`relative h-8 w-14 shrink-0 rounded-full transition ${preferences.soundEnabled !== false ? "bg-[#24745B]" : dark ? "bg-white/20" : "bg-black/25"}`}><span aria-hidden="true" className={`absolute top-1 size-6 rounded-full bg-white shadow transition-all ${preferences.soundEnabled !== false ? "left-7" : "left-1"}`}/></button></div></Section>
    <Section title="Your learning data" icon={ShieldCheck} card={card}><p className="text-sm font-semibold leading-6 opacity-55">Export a portable JSON backup before clearing browser storage or moving devices. Imports accept only AfriLingo’s versioned backup format.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Action icon={Download} onClick={downloadLearningData}>Export progress</Action><Action icon={FileUp} onClick={()=>inputRef.current?.click()}>Import progress</Action><input ref={inputRef} onChange={importFile} className="sr-only" type="file" accept="application/json,.json" aria-label="Choose AfriLingo backup"/></div>{message&&<div role="status" className="mt-3 rounded-xl bg-[#24745B]/12 p-3 text-sm font-bold">{message}</div>}</Section>
    <Section title="Privacy" icon={Info} card={card}><p className="text-sm font-semibold leading-7 opacity-60">This prototype does not create an online account, run advertising trackers, or send lesson progress to an AfriLingo server. Progress, preferences, review items, and achievements are stored in your browser. Hosting providers may retain standard access logs. Interface sounds are generated on your device. Pronunciation recording only starts when you press Record and grant microphone permission; the temporary recording stays in your browser and is discarded when cleared or when you leave the page.</p></Section>
    <Section title="Help" icon={HelpCircle} card={card}><div className="space-y-3 text-sm"><details className="rounded-xl bg-current/[.04] p-3"><summary className="cursor-pointer font-black">My progress disappeared</summary><p className="mt-2 leading-6 opacity-55">Check that you are using the same browser and device. Import a previous AfriLingo backup if browser storage was cleared.</p></details><details className="rounded-xl bg-current/[.04] p-3"><summary className="cursor-pointer font-black">Why doesn’t audio play?</summary><p className="mt-2 leading-6 opacity-55">Native-speaker audio is intentionally deferred. Text-based lessons and listening-ready practice fallbacks remain available.</p></details><details className="rounded-xl bg-current/[.04] p-3"><summary className="cursor-pointer font-black">How is language content reviewed?</summary><p className="mt-2 leading-6 opacity-55">Automated checks protect structure. Records awaiting native-speaker review remain explicitly marked and should not be treated as final editorial approval.</p></details></div></Section>
    <Section title="Help us test AfriLingo" icon={MessageSquareWarning} card={card}><TesterReport dark={dark} language={language} unit={unit}/></Section>
    <Section title="Internal production tools" icon={Mic} card={card}><p className="text-sm font-semibold leading-6 opacity-55">Record and review consented native-speaker contributions without changing live lesson data. Draft audio stays in this browser until it is explicitly downloaded and handed to the app maintainer.</p><button onClick={onOpenAudioStudio} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#4338CA] px-4 font-black text-white"><Mic size={18}/>Open Audio Contributor Studio</button></Section>
    <Section title="About AfriLingo" icon={Info} card={card}><p className="text-sm font-semibold leading-7 opacity-60">AfriLingo helps learners build practical language through structured paths, free exploration, review, and cultural context. Lebo the lion is your learning companion. Prototype version 0.2.0.</p></Section>
    <Section title="Reset progress" icon={RotateCcw} card={card}><p className="text-sm font-semibold opacity-55">These actions cannot be undone unless you export a backup first.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Action icon={RotateCcw} danger onClick={()=>{if(window.confirm(`Reset all saved ${language.language} progress?`)){resetCourseData(language.id);window.location.reload()}}}>Reset {language.language}</Action><Action icon={Trash2} danger onClick={()=>{if(window.confirm("Reset all AfriLingo progress and preferences on this device?")){resetAllLearningData();window.location.reload()}}}>Reset everything</Action></div></Section>
  </div>;
}
function Section({title,icon:Icon,card,children}){return <section className={`mt-5 rounded-[1.6rem] border p-5 ${card}`}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#F28C28]/12 text-[#F28C28]"><Icon size={20}/></span><h2 className="text-xl font-black">{title}</h2></div><div className="mt-4">{children}</div></section>}
function Action({icon:Icon,children,onClick,danger=false}){return <button onClick={onClick} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl px-4 font-black text-white ${danger?"bg-[#C95D3A]":"bg-[#24745B]"}`}><Icon size={18}/>{children}</button>}
